version: '3.4'

services:
  storagehub.api:
    image: ${DOCKER_REGISTRY-}storagehubapi
    build:
      context: .
      dockerfile: src/Dockerfile
    ports: 
     - 5000:8080
     - 5001:8081
    depends_on:
      - sql_server

  sql_server:
    restart: unless-stopped
    image: "mcr.microsoft.com/mssql/server:latest"
    container_name: sql_server
    environment:
        SA_PASSWORD: "P@ssw0rd123"
        ACCEPT_EULA: "Y"
        MSSQL_INIT_SCRIPTS: "/docker-entrypoint-initdb.d/init-db.sql"
    ports:
      - "5050:1433"
    volumes:
      - "./data-mysql:/var/opt/mysql"




